# Generated by Django 5.0.1 on 2024-06-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_costumer_cnpj_alter_costumer_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'verbose_name': ('costumer',), 'verbose_name_plural': 'costumers'},
        ),
        migrations.AlterField(
            model_name='costumer',
            name='cep',
            field=models.CharField(db_index=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='cpf',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='number',
            field=models.CharField(db_index=True, max_length=24, null=True, unique=True),
        ),
    ]
