# Generated by Django 5.0.1 on 2024-07-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_order_transaction_id_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
