# Generated by Django 5.0.1 on 2024-06-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_costumer_options_alter_costumer_cep_and_more'),
        ('products', '0005_alter_category_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='accounts.costumer'),
        ),
    ]
