# Generated by Django 5.0.1 on 2024-07-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='costumer',
        ),
    ]
